call plug#begin('~/.vim/plugged')
source ${HOME}/.vim/plugs_config/basic_conf.vim
source ${HOME}/.vim/plugs_config/vim_colorschemes.conf
source ${HOME}/.vim/plugs_config/flod_conf.vim
source ${HOME}/.vim/plugs_config/status_line_conf.vim
source ${HOME}/.vim/plugs_config/autocmd_conf.vim
source ${HOME}/.vim/plugs_config/mmaps_conf.vim
source ${HOME}/.vim/plugs_config/vim-commentary_conf.vim
source ${HOME}/.vim/plugs_config/vim-surround_conf.vim
source ${HOME}/.vim/plugs_config/vimcdoc_conf.vim
source ${HOME}/.vim/plugs_config/vim_git_conf.vim
source ${HOME}/.vim/plugs_config/lsp_client_conf.vim
source ${HOME}/.vim/plugs_config/vimcdoc_conf.vim
source ${HOME}/.vim/plugs_config/nerdtree_conf.vim
source ${HOME}/.vim/plugs_config/rainbow_conf.vim
source ${HOME}/.vim/plugs_config/fzf_conf.vim
source ${HOME}/.vim/plugs_config/c_conf.vim
source ${HOME}/.vim/plugs_config/LeaderF_conf.vim
source ${HOME}/.vim/plugs_config/tags_conf.vim
source ${HOME}/.vim/plugs_config/airline_conf.vim
source ${HOME}/.vim/plugs_config/asyncrun_conf.vim
source ${HOME}/.vim/plugs_config/easy_motion.vim
source ${HOME}/.vim/plugs_config/vim-bracketed-paste_conf.vim
call plug#end()
